### ISSUE TITLE
Popover not working in Angular 9

### ISSUE THREAD

**Issue by msalmankarim** [ivylaboratory/popover-angular#6]
I am using popover in my application. Recently I upgraded my application from Angular 7 to Angular 9 and I have noticed that popover has stop working.

![image](https://user-images.githubusercontent.com/11595290/83129160-ac2b7580-a0dc-11ea-99b3-112bfd756890.png)

Can you please look into it?

**Comment by drozhzhin-n-e** [comment]
Hey. You can download the version for Angular 8+ at the same link. Also, update the CDK overlay using the command: `npm i @ivylab/overlay-angular`

**Comment by msalmankarim** [comment]
I have downloaded the latest version but I am still getting the same error on Angular 9. It works on Angular 8 but not on Angular 9.

**Comment by msalmankarim** [comment]
Thanks
